# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ConfigLsp < Formula
  desc "Finally a LSP for your config files: gitconfig, fstab, aliases, hosts, wireguard, ssh_config, sshd_config, and more to come!"
  homepage "https://github.com/Myzel394/config-lsp"
  version "0.1.2"

  on_macos do
    on_intel do
      url "https://github.com/Myzel394/config-lsp/releases/download/v0.1.2/config-lsp_Darwin_x86_64.tar.gz"
      sha256 "6843fb7d1e3f39cb1d8ded4cb5d5b98316f22e303b381fac65ec41f24de4d4cc"

      def install
        bin.install "config-lsp"
      end
    end
    on_arm do
      url "https://github.com/Myzel394/config-lsp/releases/download/v0.1.2/config-lsp_Darwin_arm64.tar.gz"
      sha256 "6fbe8f3c5d4a6f6f6b95e299f6fe8e18ea0224f5a2519f7d7ec8d76106ea4ba8"

      def install
        bin.install "config-lsp"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Myzel394/config-lsp/releases/download/v0.1.2/config-lsp_Linux_x86_64.tar.gz"
        sha256 "7ef0a16e58d6f64aae2c6dc9bf11d4c2abff4d732c2012b9eae8596f0533a54f"

        def install
          bin.install "config-lsp"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Myzel394/config-lsp/releases/download/v0.1.2/config-lsp_Linux_arm64.tar.gz"
        sha256 "8fa2bbbda64a24b2f2c30342422657242e8f372967788f4a565433204c6855ab"

        def install
          bin.install "config-lsp"
        end
      end
    end
  end
end
