# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ConfigLsp < Formula
  desc "Finally a LSP for your config files: gitconfig, fstab, aliases, hosts, wireguard, ssh_config, sshd_config, and more to come!"
  homepage "https://github.com/Myzel394/config-lsp"
  version "0.1.1"

  on_macos do
    on_intel do
      url "https://github.com/Myzel394/config-lsp/releases/download/v0.1.1/config-lsp_Darwin_x86_64.tar.gz"
      sha256 "2d5760b510ada0cfd26f1e2185329679c182ea15e026f578d6d1f4403d2ac8d6"

      def install
        bin.install "config-lsp"
      end
    end
    on_arm do
      url "https://github.com/Myzel394/config-lsp/releases/download/v0.1.1/config-lsp_Darwin_arm64.tar.gz"
      sha256 "e5f0bd97b50661a7f645847fa2caf6b3f3deb05c0e8520d10bed7bbbaa32d7b1"

      def install
        bin.install "config-lsp"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Myzel394/config-lsp/releases/download/v0.1.1/config-lsp_Linux_x86_64.tar.gz"
        sha256 "a937ba13a718dbc6ce29195c5ba3d13adfede7ff0b10a9de374bab80becd6828"

        def install
          bin.install "config-lsp"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Myzel394/config-lsp/releases/download/v0.1.1/config-lsp_Linux_arm64.tar.gz"
        sha256 "60907c0c2df274c8a28d576a7f3b06ca7f3b50f24301f4191314c83725e2bd6f"

        def install
          bin.install "config-lsp"
        end
      end
    end
  end
end
